//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public string Barcode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Shelf { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> PiecesPerPack { get; set; }
        public Nullable<decimal> SalePricePerPiece { get; set; }
        public Nullable<decimal> OtherBonus { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public Nullable<int> ItemTypeID { get; set; }
        public string Packing { get; set; }
        public Nullable<int> PackSize { get; set; }
        public string GenericName { get; set; }
        public Nullable<int> PurchasePercentage { get; set; }
        public Nullable<int> SalePercentage { get; set; }
        public Nullable<int> TotalStock { get; set; }
        public Nullable<int> LooseQuantitySold { get; set; }
        public Nullable<int> SpecialDiscount { get; set; }
        public Nullable<int> StripPerPack { get; set; }
        public Nullable<int> TabPerStrip { get; set; }
        public Nullable<int> TotalItemPerPack { get; set; }
        public Nullable<int> LowStockQuantity { get; set; }
        public Nullable<int> CriticalLowStockQuantity { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ItemType ItemType { get; set; }
    }
}
