//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSaleItemSale
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Expr1 { get; set; }
        public int Expr2 { get; set; }
        public Nullable<System.DateTime> DateOfSale { get; set; }
        public Nullable<decimal> TotalBeforePercentage { get; set; }
        public Nullable<decimal> TotalAfterPercentage { get; set; }
        public Nullable<int> AmountPaid { get; set; }
        public Nullable<decimal> Arears { get; set; }
        public Nullable<int> SalePercentage { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> SpecialDiscount { get; set; }
    }
}
