//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleReturnItem
    {
        public int ID { get; set; }
        public Nullable<int> SaleReturnID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> SalePercentage { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string LoosePack { get; set; }
    
        public virtual SaleReturn SaleReturn { get; set; }
    }
}
