//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleReturn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleReturn()
        {
            this.SaleReturnItems = new HashSet<SaleReturnItem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> DateOfSaleReturn { get; set; }
        public Nullable<decimal> TotalBeforePercentage { get; set; }
        public Nullable<decimal> TotalAfterPercentage { get; set; }
        public Nullable<int> AmountPaid { get; set; }
        public Nullable<decimal> Arears { get; set; }
        public Nullable<int> SpecialDiscount { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleReturnItem> SaleReturnItems { get; set; }
    }
}
